### ISSUE TITLE
explain the differences between status on the identification page

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantSelBreedGame#12]
Before the breeder is identified, the file `ui_id.R` should contain explanations about the differences between being `game master`, `tester` or `player`.

**Comment by juliendiot42** [comment]
Hi !
I add the following lines under the "log in" button of the Identification tab:


Breeders can have differnts status:
- **Game-Master:** Highest privilege. You have access to "admin" and "evaluation" tabs. Your data files are available without any time restriction.
- **Tester:** Is for people who want to test this game. You have access to "evaluation" tab and your data files are available without any time restriction.
- **Player:** You have neither access to "admin" nor "evaluation" tabs. Your data file are under time restriction.

(I will merge the modification on master branch and close this issue after your approvment).

**Comment by timflutre** [comment]
Thanks, you can merge.

Remark:

-  replace "differnts status" by "different statuses"

**Comment by timflutre** [comment]
I did minor modifications (see commit just above). But even before them, the identification didn't work on my computer, even for 'test'. Did it work for you?
