### ISSUE TITLE
check that there always exists "admin" as "game master"

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantSelBreedGame#16]
At the very beginning of the appli, it should check that a player named "test" with the "tester" status exists. I will modify the `setup.Rmd` accordingly so that the data.zip it generates always has a "test" breeder inside.

**Comment by juliendiot42** [comment]
Would it not be better to check that there always exists "admin" with "game master" status than a tester ?

**Comment by timflutre** [comment]
As discussed with Julien, indeed he is right, the game should check that there always exist a player named "admin" with the status of "game master".

**Comment by timflutre** [comment]
Done in commit [ea22dd5](https://github.com/timflutre/PlantSelBreedGame/commit/ea22dd58ce55c51edcee48e609f0d40b8f685489).
