### ISSUE TITLE
allow a "tester" to create a game master if none exists

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantSelBreedGame#17]
This means that the "Admin" tab should be available to the "tester" only if no "game master" exists.

**Comment by juliendiot42** [comment]
Just for information, the case where no "game master" exists shouldn't happen :

The "admin"  breeder (with "game master" status) is created with with the game installation (when the database is created) and it is impossible to delete this breeder in the game (in admin tab):

See file [`server_admin.R`](https://github.com/timflutre/PlantSelBreedGame/blob/develop/src/server_admin.R) (develop branch) lines 77 to 81:
```r
    }else if (input$delBreederName=="admin") {
        progressDelBreeder$set(value = 0,
                               message = "Deleting breeder",
                               detail = "Sorry, admin can't be deleted.")
    }

```


Unless someone delete the "admin" breeder directly in the database, this breeder should always be here.

**Comment by timflutre** [comment]
As discussed with Julien, this task isn't relevant anymore.
