### ISSUE TITLE
improve the "year" effects

### ISSUE THREAD

**Issue by timflutre** [timflutre/PlantSelBreedGame#3]
Several partial requests for phenotyping, the same year, by the same player, should have the same "year" effects.

**Comment by juliendiot42** [comment]
the code is quite simple:
```yearEffectSeed <- 42 # should be a variable from game setup
  set.seed(yearEffectSeed+year) # seed depend of the year
  Alpha <- matrix(c(stats::rnorm(n=1, mean=0, sd=sqrt(p0$sigma.alpha2[1])),
                    stats::rnorm(n=1, mean=0, sd=sqrt(p0$sigma.alpha2[2]))),
                  nrow=1, ncol=T,
                  dimnames=list(year, c("trait1","trait2")))
  set.seed(Sys.time()) # remove seed
```

**Comment by timflutre** [comment]
I have added `seed.year.effect` to `breeding-game_setup.Rmd`. So you can remove `yearEffectSeed <- 42` from the code and use `seed.year.effect` instead of `yearEffectSeed`.

Can you also allow the game master to change this seed from the `Admin` tab?

**Comment by timflutre** [comment]
It looks ok, so I close this issue.
